name: ci-cd

on:
  push:
    branches:
    - '*'
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-python:

    # runs-on: ubuntu-20.04
    runs-on: self-hosted

    env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Set up Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .

    - name: Analysing the code with pylint
      run: |
        python -m pip install pylint
        pylint --output-format=text $(find -type f -name "*.py" ! -path "**/venv/**")

    - name: Analysing the code with mypy
      run: |
        python -m pip install mypy
        python -m pip install boto3-stubs
        python -m pip install pandas-stubs
        python -m pip install types-requests
        mypy src/

    - name: Run tests
      run: python -m unittest discover -s tests

    - name: Build package
      run: |
        python -m pip install build
        python -m build

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: distribution
        path: ./dist

  release-python:

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-python

    steps:

    - name: Download Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        name: distribution
        path: ./dist

    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/ewoc_dag-*.whl
          dist/ewoc_dag-*.tar.gz
