name: Verify

on:
  push:
    branches:
    - '*'

jobs:
  check-python:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Download EOTile
      uses: robinraju/release-downloader@v1.1
      with:
        repository: "WorldCereal/ewoc_eotile"
        tag: "0.2rc3"
        fileName: "eotile-0.2rc3-py3-none-any.whl"
        token: ${{ secrets.CS_ORG_TOKEN }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install eotile-0.2rc3-py3-none-any.whl
        pip install build
        pip install pylint

    - name: Analysing the code with pylint
      run: pylint --output-format=text $(find -type f -name "*.py" ! -path "**/venv/**")

    - name: Build package
      run: python -m build

#    - name: Publish package
#      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
#      with:
#        user: __token__
#        password: ${{ secrets.PYPI_API_TOKEN }}
